<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="User\**" />
    <EmbeddedResource Remove="User\**" />
    <None Remove="User\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\SAI.Domain.csproj" />
  </ItemGroup>

</Project>
